### ISSUE TITLE
Sampling strategy

### ISSUE THREAD

**Issue by VirginieBfd** [waldeland/deep_learning_forest_monitoring#2]
Hi Anders!

There is a mention of a sampling strategy within the paper [waldeland2020.pdf](https://github.com/waldeland/deep_learning_forest_monitoring/files/7625129/waldeland2020.pdf)
)

![image](https://user-images.githubusercontent.com/26381053/144034634-c129f28c-8f2d-403c-9758-ede7eba5fafc.png

How did you proceed? Did you apply a weighted mse?

Best, Virginie

**Comment by waldeland** [comment]
Hi Virginie.

I think, the sampling strategy mentioned in that paper was based on making a histogram of all tree heights in a training batch, and randomly removing pixels (= replacing them with unknown/ignore) from the over-represented tree heights. Until the histogram-bins had equal size. However, we did not use that strategy in 'this' paper (which is undergoing revision these days).
